### ISSUE TITLE
“exporter.Export(view)”  warn.

### ISSUE THREAD

**Issue by CallMeNo1** [weiyu666/RevitExportGltf#5]
hello , when i first build this program , happen this
<img width="340" alt="image" src="https://user-images.githubusercontent.com/31308101/188475862-3b16a5e0-e537-400c-a0e2-c17d03fe53e4.png">

**Comment by weiyu666** [comment]
Hello First of all, the program is OK; 1. First, check whether the environment you configured is 2018 or 2020. 2. No one knows what the problem is. What is your 72 lines of code? I guess it is "RevitExportGltfContext context=new RevitExportGltfContext (doc, sdial. FileName);" I think the problem is the API version! You should take a closer look at this (after all, the API designed by revit itself is incompatible with each other and will not be compatible with the next version)
![image](https://user-images.githubusercontent.com/22174508/190724003-f56c58c1-dffb-4829-92e1-797673287b1b.png)
